
SELECT PERID DNI, Nombre,

SUM(ISNULL([ENERO],0)) ENERO,SUM(ISNULL([ENERO_SABADO],0)) ENERO_SABADO,SUM(ISNULL([ENERO_DOMINGO],0)) ENERO_DOMINGO,SUM(ISNULL([ENERO_DESCU],0)) ENERO_DESCU,SUM(ISNULL([ENERO_ENFERM],0)) ENERO_ENFERM,SUM(ISNULL([ENERO_FALTA],0)) ENERO_FALTA,SUM(ISNULL([ENERO_LICENCIA],0)) ENERO_LICENCIA,SUM(ISNULL([ENERO_MATERNO],0)) ENERO_MATERNO,SUM(ISNULL([ENERO_SUSP],0)) ENERO_SUSP,SUM(ISNULL([ENERO_VAC],0)) ENERO_VAC,
SUM(ISNULL([FEBRERO],0)) FEBRERO,SUM(ISNULL([FEBRERO_SABADO],0)) FEBRERO_SABADO,SUM(ISNULL([ENERO_DOMINGO],0)) FEBRERO_DOMINGO,SUM(ISNULL([FEBRERO_DESCU],0)) FEBRERO_DESCU,SUM(ISNULL([FEBRERO_ENFERM],0)) FEBRERO_ENFERM,SUM(ISNULL([FEBRERO_FALTA],0)) FEBRERO_FALTA,SUM(ISNULL([FEBRERO_LICENCIA],0)) FEBRERO_LICENCIA,SUM(ISNULL([FEBRERO_MATERNO],0)) FEBRERO_MATERNO,SUM(ISNULL([FEBRERO_SUSP],0)) FEBRERO_SUSP,SUM(ISNULL([FEBRERO_VAC],0)) FEBRERO_VAC,
SUM(ISNULL([MARZO],0)) MARZO,SUM(ISNULL([MARZO_SABADO],0)) MARZO_SABADO,SUM(ISNULL([MARZO_DOMINGO],0)) MARZO_DOMINGO,SUM(ISNULL([MARZO_DESCU],0)) MARZO_DESCU,SUM(ISNULL([MARZO_ENFERM],0)) MARZO_ENFERM,SUM(ISNULL([MARZO_FALTA],0)) MARZO_FALTA,SUM(ISNULL([MARZO_LICENCIA],0)) MARZO_LICENCIA,SUM(ISNULL([MARZO_MATERNO],0)) MARZO_MATERNO,SUM(ISNULL([MARZO_SUSP],0)) MARZO_SUSP,SUM(ISNULL([MARZO_VAC],0)) MARZO_VAC,
SUM(ISNULL([ABRIL],0)) ABRIL,SUM(ISNULL([ABRIL_SABADO],0)) ABRIL_SABADO,SUM(ISNULL([ABRIL_DOMINGO],0)) ABRIL_DOMINGO,SUM(ISNULL([ABRIL_DESCU],0)) ABRIL_DESCU,SUM(ISNULL([ABRIL_ENFERM],0)) ABRIL_ENFERM,SUM(ISNULL([ABRIL_FALTA],0)) ABRIL_FALTA,SUM(ISNULL([ABRIL_LICENCIA],0)) ABRIL_LICENCIA,SUM(ISNULL([ABRIL_MATERNO],0)) ABRIL_MATERNO,SUM(ISNULL([ABRIL_SUSP],0)) ABRIL_SUSP,SUM(ISNULL([ABRIL_VAC],0)) ABRIL_VAC,
SUM(ISNULL([MAYO],0)) MAYO,SUM(ISNULL([MAYO_SABADO],0)) MAYO_SABADO,SUM(ISNULL([MAYO_DOMINGO],0)) MAYO_DOMINGO,SUM(ISNULL([MAYO_DESCU],0)) MAYO_DESCU,SUM(ISNULL([MAYO_ENFERM],0)) MAYO_ENFERM,SUM(ISNULL([MAYO_FALTA],0)) MAYO_FALTA,SUM(ISNULL([MAYO_LICENCIA],0)) MAYO_LICENCIA,SUM(ISNULL([MAYO_MATERNO],0)) MAYO_MATERNO,SUM(ISNULL([MAYO_SUSP],0)) MAYO_SUSP,SUM(ISNULL([MAYO_VAC],0)) MAYO_VAC,
SUM(ISNULL([JUNIO],0)) JUNIO,SUM(ISNULL([JUNIO_SABADO],0)) JUNIO_SABADO,SUM(ISNULL([JUNIO_DOMINGO],0)) JUNIO_DOMINGO,SUM(ISNULL([JUNIO_DESCU],0)) JUNIO_DESCU,SUM(ISNULL([JUNIO_ENFERM],0)) JUNIO_ENFERM,SUM(ISNULL([JUNIO_FALTA],0)) JUNIO_FALTA,SUM(ISNULL([JUNIO_LICENCIA],0)) JUNIO_LICENCIA,SUM(ISNULL([JUNIO_MATERNO],0)) JUNIO_MATERNO,SUM(ISNULL([JUNIO_SUSP],0)) JUNIO_SUSP,SUM(ISNULL([JUNIO_VAC],0)) JUNIO_VAC,
SUM(ISNULL([JULIO],0)) JULIO,SUM(ISNULL([JULIO_SABADO],0)) JULIO_SABADO,SUM(ISNULL([JULIO_DOMINGO],0)) JULIO_DOMINGO,SUM(ISNULL([JULIO_DESCU],0)) JULIO_DESCU,SUM(ISNULL([JULIO_ENFERM],0)) JULIO_ENFERM,SUM(ISNULL([JULIO_FALTA],0)) JULIO_FALTA,SUM(ISNULL([JULIO_LICENCIA],0)) JULIO_LICENCIA,SUM(ISNULL([JULIO_MATERNO],0)) JULIO_MATERNO,SUM(ISNULL([JULIO_SUSP],0)) JULIO_SUSP,SUM(ISNULL([JULIO_VAC],0)) JULIO_VAC,
SUM(ISNULL([AGOSTO],0)) AGOSTO,SUM(ISNULL([AGOSTO_SABADO],0)) AGOSTO_SABADO,SUM(ISNULL([AGOSTO_DOMINGO],0)) AGOSTO_DOMINGO,SUM(ISNULL([AGOSTO_DESCU],0)) AGOSTO_DESCU,SUM(ISNULL([AGOSTO_ENFERM],0)) AGOSTO_ENFERM,SUM(ISNULL([AGOSTO_FALTA],0)) AGOSTO_FALTA,SUM(ISNULL([AGOSTO_LICENCIA],0)) AGOSTO_LICENCIA,SUM(ISNULL([AGOSTO_MATERNO],0)) AGOSTO_MATERNO,SUM(ISNULL([AGOSTO_SUSP],0)) AGOSTO_SUSP,SUM(ISNULL([AGOSTO_VAC],0)) AGOSTO_VAC,
SUM(ISNULL([SETIEMBRE],0)) SETIEMBRE,SUM(ISNULL([SETIEMBRE_SABADO],0)) SETIEMBRE_SABADO,SUM(ISNULL([SETIEMBRE_DOMINGO],0)) SETIEMBRE_DOMINGO,SUM(ISNULL([SETIEMBRE_DESCU],0)) SETIEMBRE_DESCU,SUM(ISNULL([SETIEMBRE_ENFERM],0)) SETIEMBRE_ENFERM,SUM(ISNULL([SETIEMBRE_FALTA],0)) SETIEMBRE_FALTA,SUM(ISNULL([SETIEMBRE_LICENCIA],0)) SETIEMBRE_LICENCIA,SUM(ISNULL([SETIEMBRE_MATERNO],0)) SETIEMBRE_MATERNO,SUM(ISNULL([SETIEMBRE_SUSP],0)) SETIEMBRE_SUSP,SUM(ISNULL([SETIEMBRE_VAC],0)) SETIEMBRE_VAC,
SUM(ISNULL([OCTUBRE],0)) OCTUBRE,SUM(ISNULL([OCTUBRE_SABADO],0)) OCTUBRE_SABADO,SUM(ISNULL([OCTUBRE_DOMINGO],0)) OCTUBRE_DOMINGO,SUM(ISNULL([OCTUBRE_DESCU],0)) OCTUBRE_DESCU,SUM(ISNULL([OCTUBRE_ENFERM],0)) OCTUBRE_ENFERM,SUM(ISNULL([OCTUBRE_FALTA],0)) OCTUBRE_FALTA,SUM(ISNULL([OCTUBRE_LICENCIA],0)) OCTUBRE_LICENCIA,SUM(ISNULL([OCTUBRE_MATERNO],0)) OCTUBRE_MATERNO,SUM(ISNULL([OCTUBRE_SUSP],0)) OCTUBRE_SUSP,SUM(ISNULL([OCTUBRE_VAC],0)) OCTUBRE_VAC,
SUM(ISNULL([NOVIEMBRE],0)) NOVIEMBRE,SUM(ISNULL([NOVIEMBRE_SABADO],0)) NOVIEMBRE_SABADO,SUM(ISNULL([NOVIEMBRE_DOMINGO],0)) NOVIEMBRE_DOMINGO,SUM(ISNULL([NOVIEMBRE_DESCU],0)) NOVIEMBRE_DESCU,SUM(ISNULL([NOVIEMBRE_ENFERM],0)) NOVIEMBRE_ENFERM,SUM(ISNULL([NOVIEMBRE_FALTA],0)) NOVIEMBRE_FALTA,SUM(ISNULL([NOVIEMBRE_LICENCIA],0)) NOVIEMBRE_LICENCIA,SUM(ISNULL([NOVIEMBRE_MATERNO],0)) NOVIEMBRE_MATERNO,SUM(ISNULL([NOVIEMBRE_SUSP],0)) NOVIEMBRE_SUSP,SUM(ISNULL([NOVIEMBRE_VAC],0)) NOVIEMBRE_VAC,
SUM(ISNULL([DICIEMBRE],0)) DICIEMBRE,SUM(ISNULL([DICIEMBRE_SABADO],0)) DICIEMBRE_SABADO,SUM(ISNULL([DICIEMBRE_DOMINGO],0)) DICIEMBRE_DOMINGO,SUM(ISNULL([DICIEMBRE_DESCU],0)) DICIEMBRE_DESCU,SUM(ISNULL([DICIEMBRE_ENFERM],0)) DICIEMBRE_ENFERM,SUM(ISNULL([DICIEMBRE_FALTA],0)) DICIEMBRE_FALTA,SUM(ISNULL([DICIEMBRE_LICENCIA],0)) DICIEMBRE_LICENCIA,SUM(ISNULL([DICIEMBRE_MATERNO],0)) DICIEMBRE_MATERNO,SUM(ISNULL([DICIEMBRE_SUSP],0)) DICIEMBRE_SUSP,SUM(ISNULL([DICIEMBRE_VAC],0)) DICIEMBRE_VAC

FROM  
(

-- LICENCIA
SELECT A.perid, A.nombre, A.estado, CAST(1 AS INT) MARCA,
(CASE 
WHEN DATENAME(MONTH,B.fecha) = 'January' THEN 'ENERO_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'February' THEN 'FEBRERO_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'March' THEN 'MARZO_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'April' THEN 'ABRIL_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'May' THEN 'MAYO_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'June' THEN 'JUNIO_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'July' THEN 'JULIO_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'August' THEN 'AGOSTO_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'September' THEN 'SETIEMBRE_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'October' THEN 'OCTUBRE_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'November' THEN 'NOVIEMBRE_LICENCIA'
WHEN DATENAME(MONTH,B.fecha) = 'December' THEN 'DICIEMBRE_LICENCIA'
ELSE '' END) MES --, CASE WHEN THEN ELSE END
from PAAsistD A
INNER JOIN PAAsistH B ON A.asistid = B.asistid
WHERE B.perpost >= '202001' AND B.perpost <= '202012' --AND perid = '72130767'
AND A.estado = 0

UNION ALL

/*
-- ASISTIO
SELECT A.perid, A.nombre, A.estado, CAST(1 AS INT) MARCA,
(CASE 
WHEN DATENAME(MONTH,B.fecha) = 'January' THEN 'ENERO'
WHEN DATENAME(MONTH,B.fecha) = 'February' THEN 'FEBRERO'
WHEN DATENAME(MONTH,B.fecha) = 'March' THEN 'MARZO'
WHEN DATENAME(MONTH,B.fecha) = 'April' THEN 'ABRIL'
WHEN DATENAME(MONTH,B.fecha) = 'May' THEN 'MAYO'
WHEN DATENAME(MONTH,B.fecha) = 'June' THEN 'JUNIO'
WHEN DATENAME(MONTH,B.fecha) = 'July' THEN 'JULIO'
WHEN DATENAME(MONTH,B.fecha) = 'August' THEN 'AGOSTO'
WHEN DATENAME(MONTH,B.fecha) = 'September' THEN 'SETIEMBRE'
WHEN DATENAME(MONTH,B.fecha) = 'October' THEN 'OCTUBRE'
WHEN DATENAME(MONTH,B.fecha) = 'November' THEN 'NOVIEMBRE'
WHEN DATENAME(MONTH,B.fecha) = 'December' THEN 'DICIEMBRE'
ELSE '' END) MES --, CASE WHEN THEN ELSE END
from PAAsistD A
INNER JOIN PAAsistH B ON A.asistid = B.asistid
WHERE B.perpost >= '202001' AND B.perpost <= '202012' --AND perid = '72130767'
AND A.estado = 1
*/

-- ASISTIO
SELECT A.perid, A.nombre, A.estado, CAST(1 AS INT) MARCA,
(CASE 
WHEN DATENAME(MONTH,B.fecha) = 'January' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'ENERO_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'ENERO_DOMINGO' ELSE 'ENERO' END) END) 
WHEN DATENAME(MONTH,B.fecha) = 'February' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'FEBRERO_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'FEBRERO_DOMINGO' ELSE 'FEBRERO' END) END)
WHEN DATENAME(MONTH,B.fecha) = 'March' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'MARZO_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'MARZO_DOMINGO' ELSE 'MARZO' END) END)
WHEN DATENAME(MONTH,B.fecha) = 'April' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'ABRIL_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'ABRIL_DOMINGO' ELSE 'ABRIL' END) END)
WHEN DATENAME(MONTH,B.fecha) = 'May' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'MAYO_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'MAYO_DOMINGO' ELSE 'MAYO' END) END)
WHEN DATENAME(MONTH,B.fecha) = 'June' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'JUNIO_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'JUNIO_DOMINGO' ELSE 'JUNIO' END) END)
WHEN DATENAME(MONTH,B.fecha) = 'July' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'JULIO_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'JULIO_DOMINGO' ELSE 'JULIO' END) END)
WHEN DATENAME(MONTH,B.fecha) = 'August' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'AGOSTO_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'AGOSTO_DOMINGO' ELSE 'AGOSTO' END) END)
WHEN DATENAME(MONTH,B.fecha) = 'September' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'SETIEMBRE_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'SETIEMBRE_DOMINGO' ELSE 'SETIEMBRE' END) END)
WHEN DATENAME(MONTH,B.fecha) = 'October' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'OCTUBRE_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'OCTUBRE_DOMINGO' ELSE 'OCTUBRE' END) END)
WHEN DATENAME(MONTH,B.fecha) = 'November' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'NOVIEMBRE_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'NOVIEMBRE_DOMINGO' ELSE 'NOVIEMBRE' END) END)
WHEN DATENAME(MONTH,B.fecha) = 'December' THEN (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'saturday' THEN 'DICIEMBRE_SABADO' ELSE (CASE WHEN DATENAME(WEEKDAY,B.fecha) = 'sunday' THEN 'DICIEMBRE_DOMINGO' ELSE 'DICIEMBRE' END) END)
ELSE '' END) MES --, CASE WHEN THEN ELSE END
from PAAsistD A
INNER JOIN PAAsistH B ON A.asistid = B.asistid
WHERE B.perpost >= '202001' AND B.perpost <= '202012' 
--AND perid = '72130767'
AND A.estado = 1

UNION ALL

-- FALTA
SELECT A.perid, A.nombre, A.estado, CAST(1 AS INT) MARCA,
(CASE 
WHEN DATENAME(MONTH,B.fecha) = 'January' THEN 'ENERO_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'February' THEN 'FEBRERO_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'March' THEN 'MARZO_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'April' THEN 'ABRIL_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'May' THEN 'MAYO_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'June' THEN 'JUNIO_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'July' THEN 'JULIO_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'August' THEN 'AGOSTO_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'September' THEN 'SETIEMBRE_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'October' THEN 'OCTUBRE_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'November' THEN 'NOVIEMBRE_FALTA'
WHEN DATENAME(MONTH,B.fecha) = 'December' THEN 'DICIEMBRE_FALTA'
ELSE '' END) MES --, CASE WHEN THEN ELSE END
from PAAsistD A
INNER JOIN PAAsistH B ON A.asistid = B.asistid
WHERE B.perpost >= '202001' AND B.perpost <= '202012' --AND perid = '72130767'
AND A.estado = 3

UNION ALL

-- VACACIONES
SELECT A.perid, A.nombre, A.estado, CAST(1 AS INT) MARCA,
(CASE 
WHEN DATENAME(MONTH,B.fecha) = 'January' THEN 'ENERO_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'February' THEN 'FEBRERO_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'March' THEN 'MARZO_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'April' THEN 'ABRIL_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'May' THEN 'MAYO_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'June' THEN 'JUNIO_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'July' THEN 'JULIO_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'August' THEN 'AGOSTO_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'September' THEN 'SETIEMBRE_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'October' THEN 'OCTUBRE_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'November' THEN 'NOVIEMBRE_VAC'
WHEN DATENAME(MONTH,B.fecha) = 'December' THEN 'DICIEMBRE_VAC'
ELSE '' END) MES --, CASE WHEN THEN ELSE END
from PAAsistD A
INNER JOIN PAAsistH B ON A.asistid = B.asistid
WHERE B.perpost >= '202001' AND B.perpost <= '202012' --AND perid = '72130767'
AND A.estado = 4

--SELECT * FROM PAPermisoVacacion WHERE PERID = '72130767' AND fechainicio > = '2020-01-01' AND fechafin <= '2020-12-01'

UNION ALL

-- DESCUENTOS
SELECT A.perid, A.nombre, A.estado, CAST(1 AS INT) MARCA,
(CASE 
WHEN DATENAME(MONTH,B.fecha) = 'January' THEN 'ENERO_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'February' THEN 'FEBRERO_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'March' THEN 'MARZO_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'April' THEN 'ABRIL_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'May' THEN 'MAYO_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'June' THEN 'JUNIO_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'July' THEN 'JULIO_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'August' THEN 'AGOSTO_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'September' THEN 'SETIEMBRE_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'October' THEN 'OCTUBRE_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'November' THEN 'NOVIEMBRE_DESCU'
WHEN DATENAME(MONTH,B.fecha) = 'December' THEN 'DICIEMBRE_DESCU'
ELSE '' END) MES --, CASE WHEN THEN ELSE END
from PAAsistD A
INNER JOIN PAAsistH B ON A.asistid = B.asistid
WHERE B.perpost >= '202001' AND B.perpost <= '202012' --AND perid = '72130767'
AND A.estado = 5

UNION ALL

-- SUSPENCION (CON O SIN GOZE)
SELECT A.perid, A.nombre, A.estado, CAST(1 AS INT) MARCA,
(CASE 
WHEN DATENAME(MONTH,B.fecha) = 'January' THEN 'ENERO_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'February' THEN 'FEBRERO_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'March' THEN 'MARZO_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'April' THEN 'ABRIL_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'May' THEN 'MAYO_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'June' THEN 'JUNIO_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'July' THEN 'JULIO_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'August' THEN 'AGOSTO_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'September' THEN 'SETIEMBRE_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'October' THEN 'OCTUBRE_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'November' THEN 'NOVIEMBRE_SUSP'
WHEN DATENAME(MONTH,B.fecha) = 'December' THEN 'DICIEMBRE_SUSP'
ELSE '' END) MES --, CASE WHEN THEN ELSE END
from PAAsistD A
INNER JOIN PAAsistH B ON A.asistid = B.asistid
WHERE B.perpost >= '202001' AND B.perpost <= '202012' --AND perid = '72130767'
AND A.estado = 6

UNION ALL

-- SUBSIDIO MATERNO
SELECT A.perid, A.nombre, A.estado, CAST(1 AS INT) MARCA,
(CASE 
WHEN DATENAME(MONTH,B.fecha) = 'January' THEN 'ENERO_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'February' THEN 'FEBRERO_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'March' THEN 'MARZO_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'April' THEN 'ABRIL_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'May' THEN 'MAYO_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'June' THEN 'JUNIO_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'July' THEN 'JULIO_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'August' THEN 'AGOSTO_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'September' THEN 'SETIEMBRE_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'October' THEN 'OCTUBRE_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'November' THEN 'NOVIEMBRE_MATERNO'
WHEN DATENAME(MONTH,B.fecha) = 'December' THEN 'DICIEMBRE_MATERNO'
ELSE '' END) MES --, CASE WHEN THEN ELSE END
from PAAsistD A
INNER JOIN PAAsistH B ON A.asistid = B.asistid
WHERE B.perpost >= '202001' AND B.perpost <= '202012' --AND perid = '72130767'
AND A.estado = 8

UNION ALL

-- SUBSIDIO POR INCAPACIDAD
SELECT A.perid, A.nombre, A.estado, CAST(1 AS INT) MARCA,
(CASE 
WHEN DATENAME(MONTH,B.fecha) = 'January' THEN 'ENERO_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'February' THEN 'FEBRERO_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'March' THEN 'MARZO_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'April' THEN 'ABRIL_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'May' THEN 'MAYO_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'June' THEN 'JUNIO_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'July' THEN 'JULIO_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'August' THEN 'AGOSTO_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'September' THEN 'SETIEMBRE_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'October' THEN 'OCTUBRE_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'November' THEN 'NOVIEMBRE_ENFERM'
WHEN DATENAME(MONTH,B.fecha) = 'December' THEN 'DICIEMBRE_ENFERM'
ELSE '' END) MES --, CASE WHEN THEN ELSE END
from PAAsistD A
INNER JOIN PAAsistH B ON A.asistid = B.asistid
WHERE B.perpost >= '202001' AND B.perpost <= '202012' --AND perid = '72130767'
AND A.estado = 9

/*
UNION ALL


SELECT A.perid, A.nombre, A.estado, CAST(1 AS INT) MARCA,
(CASE 
WHEN DATENAME(MONTH,B.fecha) = 'January' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'January' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'January' and A.estado = 3 THEN 'ENERO_FALTA' ELSE 'ENERO_VAC' END) ELSE 'ENERO' END)
WHEN DATENAME(MONTH,B.fecha) = 'February' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'February' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'February' and A.estado = 3 THEN 'FEBRERO_FALTA' ELSE 'FEBRERO_VAC' END) ELSE 'FEBRERO' END)
WHEN DATENAME(MONTH,B.fecha) = 'March' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'March' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'March' and A.estado = 3 THEN 'MARZO_FALTA' ELSE 'MARZO_VAC' END) ELSE 'MARZO' END)
WHEN DATENAME(MONTH,B.fecha) = 'April' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'April' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'April' and A.estado = 3 THEN 'ABRIL_FALTA' ELSE 'ABRIL_VAC' END) ELSE 'ABRIL' END)
WHEN DATENAME(MONTH,B.fecha) = 'May' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'May' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'May' and A.estado = 3 THEN 'MAYO_FALTA' ELSE 'MAYO_VAC' END) ELSE 'MAYO' END)
WHEN DATENAME(MONTH,B.fecha) = 'June' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'June' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'June' and A.estado = 3 THEN 'JUNIO_FALTA' ELSE 'JUNIO_VAC' END) ELSE 'JUNIO' END)
WHEN DATENAME(MONTH,B.fecha) = 'July' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'July' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'July' and A.estado = 3 THEN 'JULIO_FALTA' ELSE 'JULIO_VAC' END) ELSE 'JULIO' END)
WHEN DATENAME(MONTH,B.fecha) = 'August' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'August' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'August' and A.estado = 3 THEN 'AGOSTO_FALTA' ELSE 'AGOSTO_VAC' END) ELSE 'AGOSTO' END)
WHEN DATENAME(MONTH,B.fecha) = 'September' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'September' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'September' and A.estado = 3 THEN 'SETIEMBRE_FALTA' ELSE 'SETIEMBRE_VAC' END) ELSE 'SETIEMBRE' END)
WHEN DATENAME(MONTH,B.fecha) = 'October' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'October' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'October' and A.estado = 3 THEN 'OCTUBRE_FALTA' ELSE 'OCTUBRE_VAC' END) ELSE 'OCTUBRE' END)
WHEN DATENAME(MONTH,B.fecha) = 'November' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'November' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'November' and A.estado = 3 THEN 'NOVIEMBRE_FALTA' ELSE 'NOVIEMBRE_VAC' END) ELSE 'NOVIEMBRE' END)
WHEN DATENAME(MONTH,B.fecha) = 'December' THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'December' and A.estado = 4 THEN (CASE WHEN DATENAME(MONTH,B.fecha) = 'December' and A.estado = 3 THEN 'DICIEMBRE_FALTA' ELSE 'DICIEMBRE_VAC' END) ELSE 'DICIEMBRE' END)
ELSE '' END) MES --, CASE WHEN THEN ELSE END
from PAAsistD A
INNER JOIN PAAsistH B ON A.asistid = B.asistid
WHERE B.perpost >= '202001' AND B.perpost <= '202012' --AND perid = '72130767'
*/
) AS SourceTable  
PIVOT  
(  
SUM(MARCA)  
FOR MES IN (

[ENERO],[ENERO_SABADO],[ENERO_DOMINGO],[ENERO_DESCU],[ENERO_ENFERM],[ENERO_FALTA],[ENERO_LICENCIA],[ENERO_MATERNO],[ENERO_SUSP],[ENERO_VAC],
[FEBRERO],[FEBRERO_SABADO],[FEBRERO_DOMINGO],[FEBRERO_DESCU],[FEBRERO_ENFERM],[FEBRERO_FALTA],[FEBRERO_LICENCIA],[FEBRERO_MATERNO],[FEBRERO_SUSP],[FEBRERO_VAC],
[MARZO],[MARZO_SABADO],[MARZO_DOMINGO],[MARZO_DESCU],[MARZO_ENFERM],[MARZO_FALTA],[MARZO_LICENCIA],[MARZO_MATERNO],[MARZO_SUSP],[MARZO_VAC],
[ABRIL],[ABRIL_SABADO],[ABRIL_DOMINGO],[ABRIL_DESCU],[ABRIL_ENFERM],[ABRIL_FALTA],[ABRIL_LICENCIA],[ABRIL_MATERNO],[ABRIL_SUSP],[ABRIL_VAC],
[MAYO],[MAYO_SABADO],[MAYO_DOMINGO],[MAYO_DESCU],[MAYO_ENFERM],[MAYO_FALTA],[MAYO_LICENCIA],[MAYO_MATERNO],[MAYO_SUSP],[MAYO_VAC],
[JUNIO],[JUNIO_SABADO],[JUNIO_DOMINGO],[JUNIO_DESCU],[JUNIO_ENFERM],[JUNIO_FALTA],[JUNIO_LICENCIA],[JUNIO_MATERNO],[JUNIO_SUSP],[JUNIO_VAC],
[JULIO],[JULIO_SABADO],[JULIO_DOMINGO],[JULIO_DESCU],[JULIO_ENFERM],[JULIO_FALTA],[JULIO_LICENCIA],[JULIO_MATERNO],[JULIO_SUSP],[JULIO_VAC],
[AGOSTO],[AGOSTO_SABADO],[AGOSTO_DOMINGO],[AGOSTO_DESCU],[AGOSTO_ENFERM],[AGOSTO_FALTA],[AGOSTO_LICENCIA],[AGOSTO_MATERNO],[AGOSTO_SUSP],[AGOSTO_VAC],
[SETIEMBRE],[SETIEMBRE_SABADO],[SETIEMBRE_DOMINGO],[SETIEMBRE_DESCU],[SETIEMBRE_ENFERM],[SETIEMBRE_FALTA],[SETIEMBRE_LICENCIA],[SETIEMBRE_MATERNO],[SETIEMBRE_SUSP],[SETIEMBRE_VAC],
[OCTUBRE],[OCTUBRE_SABADO],[OCTUBRE_DOMINGO],[OCTUBRE_DESCU],[OCTUBRE_ENFERM],[OCTUBRE_FALTA],[OCTUBRE_LICENCIA],[OCTUBRE_MATERNO],[OCTUBRE_SUSP],[OCTUBRE_VAC],
[NOVIEMBRE],[NOVIEMBRE_SABADO],[NOVIEMBRE_DOMINGO],[NOVIEMBRE_DESCU],[NOVIEMBRE_ENFERM],[NOVIEMBRE_FALTA],[NOVIEMBRE_LICENCIA],[NOVIEMBRE_MATERNO],[NOVIEMBRE_SUSP],[NOVIEMBRE_VAC],
[DICIEMBRE],[DICIEMBRE_SABADO],[DICIEMBRE_DOMINGO],[DICIEMBRE_DESCU],[DICIEMBRE_ENFERM],[DICIEMBRE_FALTA],[DICIEMBRE_LICENCIA],[DICIEMBRE_MATERNO],[DICIEMBRE_SUSP],[DICIEMBRE_VAC]

)  
) AS PivotTable
--WHERE PERID = '77683117'
GROUP BY perid, nombre
