

SELECT DOCDATE,duedate,discdate,REFNBR,*  FROM ARDOC WHERE BATNBR ='021731'  AND MONTH(DOCDATE)  = 6 and custid ='00000000000'

update ardoc set discdate  = docdate , duedate =docdate where batnbr  ='021731' 



DECLARE @newMonth int
SET @newMonth = 6 --As an example
UPDATE ARDOC
SET DOCDATE = DATEADD(month, @newMonth - DATEPART(month, DOCDATE) , DOCDATE) WHERE BATNBR ='021731'


DECLARE @newMonth int
SET @newMonth = 6 --As an example
UPDATE artran
SET trandate = DATEADD(month, @newMonth - DATEPART(month, trandate) , trandate) WHERE BATNBR ='021731'


SELECT docdate,SUBSTRING (  LEFT(CONVERT(VARCHAR, docdate, 120), 10),0,5) +'-06-'+SUBSTRING( LEFT(CONVERT(VARCHAR, docdate, 120), 10),6,2) AS FECHACORRECTA 
--UPDATE ARDOC SET docdate  = SUBSTRING (  LEFT(CONVERT(VARCHAR, docdate, 120), 10),0,5) +'-05-'+SUBSTRING( LEFT(CONVERT(VARCHAR, docdate, 120), 10),6,2)
 FROM ARDOC WHERE BATNBR ='021731'  AND MONTH(docdate) = 5
 


SELECT TRANDATE,SUBSTRING (  LEFT(CONVERT(VARCHAR, TRANDATE, 120), 10),0,5) +'-06-'+SUBSTRING( LEFT(CONVERT(VARCHAR, TRANDATE, 120), 10),6,2) AS FECHACORRECTA 
--UPDATE ARTRAN SET TRANDATE  = SUBSTRING (  LEFT(CONVERT(VARCHAR, TRANDATE, 120), 10),0,5) +'-05-'+SUBSTRING( LEFT(CONVERT(VARCHAR, TRANDATE, 120), 10),6,2)
 FROM ARTRAN WHERE BATNBR ='021731'  AND MONTH(TRANDATE) <> 6
 
 UPDATE ARDOC SET MONTH(DOCDATE ) = 6 WHERE BATNBR ='021731'
 

SELECT FECHANEGOCIO,SUBSTRING (  LEFT(CONVERT(VARCHAR, FECHANEGOCIO, 120), 10),0,5) +'-05-'+SUBSTRING( LEFT(CONVERT(VARCHAR, FECHANEGOCIO, 120), 10),6,2) AS FECHACORRECTA 
--UPDATE ARTRAN SET TRANDATE  = SUBSTRING (  LEFT(CONVERT(VARCHAR, TRANDATE, 120), 10),0,5) +'-05-'+SUBSTRING( LEFT(CONVERT(VARCHAR, TRANDATE, 120), 10),6,2)
 FROM CF_REGVTAS WHERE EXPORTADOFN ='018222'  --AND MONTH(FECHANEGOCIO) <> 5
 
 
 
SELECT B.DOCDATE,A.TRANDATE 
--UPDATE ARDOC SET docdate  =
FROM ARTRAN A 
INNER JOIN ARDOC B ON A.BATNBR  = B.BATNBR 
WHERE B.BATNBR ='018222'