


SELECT * FROM COMISIONDETALLE WHERE PERIODOID <= '202007' AND PERID = '70670868'

       
SELECT top 100 PERIODOID,PERID,'VAC' AS TIPO ,BD.CANTIDAD,CASE WHEN PERIODOID='202007' THEN 0 ELSE 0 END  AS COMMES   , BD.user7 as ProduccionVaca, BD.cantidad+BD.user7 as TotalProduccion          
FROM PABOLETAH BH INNER JOIN PABOLETAD BD ON BH.NBRBOLETA=BD.NBRBOLETA             
WHERE BH.PERID= '70670868'  AND BD.RUBID='R03' AND BH.PERIODOID IN ( SELECT DISTINCT  TOP 100 PERIODOID FROM PABOLETAH              
WHERE   PerID= BH.perid  and  PERTIPOPAGO<>'GR' AND PERIODOID<= '202007'  ORDER BY PERIODOID DESC )            
ORDER BY PERIODOID DESC



