ALTER PROC Z_MARCACION_X_DNI
-- SISTEMA : ASISTENCIA 2020
-- FUNCION : PROCEDURE MARCACION POR DNI AL PERSONAL
-- FECHA   : 2020-08-14
-- USUARIO : JOSEPH MAGALLANES NOLAZCO   
@PER_COD VARCHAR(15)    
AS    
BEGIN    

DECLARE @ESTADO INT
--DECLARE @TIPO_DOCUMENTO INT
DECLARE @MARCA_DNI INT
DECLARE @MARCACION_INSERTADA INT

--MARCACION (PREGUNTAMO SI SU ESTADO ESTA ACTIVO PARA MARCA)
SET @ESTADO = (SELECT ISNULL(COUNT(*),0) DATO FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end) AND ESTADO = 'ACTIVO')

----TIPO DOCUMENTO
--SET @TIPO_DOCUMENTO = (SELECT ISNULL(COUNT(*),0) DATO FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end) AND ESTADO = 'ACTIVO')

--PARA SABER SI TIENE ACCESO A MARCAR POR DNI
SET @MARCA_DNI = (SELECT ISNULL(COUNT(*),0) FROM PERSONAL WHERE PER_COD = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end) AND MAR_DNI = 1)

--PARA SABER SI YA SE INSETO LA MARCACION
SET @MARCACION_INSERTADA = (SELECT ISNULL(COUNT(*),0) FROM ASISTENCIA_TEMP WHERE PER_COD = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end) AND COMENTARIO = 'FALTO')


IF @ESTADO = 0    
	BEGIN
		DECLARE @TIPO_ESTADO VARCHAR(50)
		SET @TIPO_ESTADO = (SELECT LTRIM(RTRIM((ESTADO))) ESTADO FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end))
		--PREGUNTAMOS PARA OBTENER ESTADO
		IF (SELECT LTRIM(RTRIM((ESTADO))) ESTADO FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end)) <> 'ACTIVO'
			BEGIN
				SELECT LTRIM(RTRIM(PERID)) PER_COD,     
				LTRIM(RTRIM(LTRIM(RTRIM(PERNOMBRE))+' '    
				+LTRIM(RTRIM(PERPATERNO))+' '+LTRIM(RTRIM(PERMATERNO)))) NOMBRES,    
				'UDS. ESTA DE ' + LTRIM(RTRIM(@TIPO_ESTADO)) + '. NO PUEDE MARCAR' MENSAJE, 3 xCond, 0 Button, 0 MHUELLA, 0 MDNI 
				FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end)     
			END
	END    
ELSE    
	IF @MARCA_DNI = 0    
		BEGIN    
			SELECT LTRIM(RTRIM(PERID)) PER_COD,     
			LTRIM(RTRIM(LTRIM(RTRIM(PERNOMBRE))+' '    
			+LTRIM(RTRIM(PERPATERNO))+' '+LTRIM(RTRIM(PERMATERNO)))) NOMBRES,    
			'NO TIENE ACCESO A MARCAR CON DNI' MENSAJE, 0 xCond, 0 Button, 0 MHUELLA, 0 MDNI 
			FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end)     
		END    
	ELSE    
		IF @MARCA_DNI = 1    
			BEGIN    
				IF @MARCACION_INSERTADA = 1
					BEGIN    
						SELECT LTRIM(RTRIM(PERID)) PER_COD,     
						LTRIM(RTRIM(LTRIM(RTRIM(PERNOMBRE))+' '    
						+LTRIM(RTRIM(PERPATERNO))+' '+LTRIM(RTRIM(PERMATERNO)))) NOMBRES,    
						'REGISTRAR ENTRADA ?' MENSAJE, 1 xCond, 1 Button, 0 MHUELLA, 1 MDNI 
						FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end)     
					END    
				ELSE    
					IF (SELECT COUNT(*) FROM ASISTENCIA_TEMP WHERE FECHA = CONVERT(VARCHAR(10),GETDATE(),120) AND 
						PER_COD = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end) AND EST_REF = 'N' AND EST_ASIS = 'I') = 1    
						BEGIN    
							SELECT LTRIM(RTRIM(PERID)) PER_COD,     
							LTRIM(RTRIM(LTRIM(RTRIM(PERNOMBRE))+' '    
							+LTRIM(RTRIM(PERPATERNO))+' '+LTRIM(RTRIM(PERMATERNO)))) NOMBRES,    
							'INICIO DE REFRIGERIO ?' MENSAJE, 1 xCond, 2 Button, 0 MHUELLA, 1 MDNI 
							FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end)     
						END    
					ELSE    
						IF (SELECT COUNT(*) FROM ASISTENCIA_TEMP WHERE FECHA = CONVERT(VARCHAR(10),GETDATE(),120) AND 
							PER_COD = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end) AND EST_REF = 'I' AND EST_ASIS = 'I') = 1    
							BEGIN    
								SELECT LTRIM(RTRIM(PERID)) PER_COD,     
								LTRIM(RTRIM(LTRIM(RTRIM(PERNOMBRE))+' '    
								+LTRIM(RTRIM(PERPATERNO))+' '+LTRIM(RTRIM(PERMATERNO)))) NOMBRES,    
								'TERMINO DE REFRIGERIO ?' MENSAJE, 1 xCond, 3 Button, 0 MHUELLA, 1 MDNI 
								FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end)     
							END    
						ELSE    
							IF (SELECT COUNT(*) FROM ASISTENCIA_TEMP WHERE FECHA = CONVERT(VARCHAR(10),GETDATE(),120) AND 
								PER_COD = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end) AND EST_REF = 'T' AND EST_ASIS = 'I') = 1    
								BEGIN    
									SELECT LTRIM(RTRIM(PERID)) PER_COD,     
									LTRIM(RTRIM(LTRIM(RTRIM(PERNOMBRE))+' '    
									+LTRIM(RTRIM(PERPATERNO))+' '+LTRIM(RTRIM(PERMATERNO)))) NOMBRES,    
									'REGISTRAR SALIDA ?' MENSAJE, 1 xCond, 4 Button, 0 MHUELLA, 1 MDNI 
									FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end)     
								END    
							ELSE    
								IF (SELECT COUNT(*) FROM ASISTENCIA_TEMP WHERE FECHA = CONVERT(VARCHAR(10),GETDATE(),120) AND 
									PER_COD = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end) AND EST_REF = 'T' AND EST_ASIS = 'S') = 1    
									BEGIN    
										SELECT LTRIM(RTRIM(PERID)) PER_COD,     
										LTRIM(RTRIM(LTRIM(RTRIM(PERNOMBRE))+' '    
										+LTRIM(RTRIM(PERPATERNO))+' '+LTRIM(RTRIM(PERMATERNO)))) NOMBRES,    
										'UDS. YA MARCO SU SALIDA' MENSAJE, 2 xCond, 0 Button, 0 MHUELLA, 0 MDNI 
										FROM PERSONALBD WHERE PERID = (case when len(@PER_COD)<8 then RIGHT('00000000' + Ltrim(Rtrim(@PER_COD)),8) else @PER_COD end)     
									END    
            
			END    
END 