-- VERIFICAR CUOTA DE VENDEDOR ALTOMAYO


-- SE VERIFICA POR PERIODO EN MODULO/ VENTAS / FUERAZA VENTA DIRECTA 

-- SE VERIFICA POR PERIODO ACTUAL  
-- SE VERIFICA SI EL PERIODO ESTA ABIERTO O CERRADO  
-- SE PUEDE INGRESAR EL PERIODO DE LA CUOTA POR VENDEDOR SIEMPRE Y CUANDO EL PERIODO ANTERIOR ESTE CERRADO
-- INGRESAR CUOTA POR PERIODO BAJO REQUERIMIENTO 
-- EJECUTAR JOBS 51 (llenartb_ventas/llenarpfvd)

--FINALMENTE SE VERIFICA EN EL REPORTE (MODULE/VENTAS/R/PRESUPUESTO FUERZA DIRECTA - DIA ANTERIOR / ULTIMO REPORTE)

-- ENVIAR POR PDF












