


--- CAMBIAR A DOBLE TIPO DE CAMBIO PARA CUENTA --

SELECT * FROM ACCOUNT WHERE ACCT ='169801'

UPDATE ACCOUNT SET CURYID ='' WHERE ACCT ='999997'

SELECT* FROM CASHACCT ORDER BY BANKSUB ASC


SELECT* FROM BANKACCT