USE [AM2014APP]
GO
SELECT DISTINCT TIPO  FROM XAMRESTRICCION
---TABLA RESTRICCION_TIPO


CREATE TABLE TB_RESTRICCIONTIPO
(
TIPO VARCHAR(15) NULL,
DESCRIPCION_TIPO VARCHAR(100) NULL,
TSTAMP TIMESTAMP NULL
)
CREATE UNIQUE CLUSTERED INDEX TB_RESTRICCIONTIPO0 ON TB_RESTRICCIONTIPO(TIPO)

DROP INDEX PK_XAMRESTRICCION
create unique clustered index xAMRestriccion0 on xAMRestriccion(USERID)

INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('FACTURARTOTTUS','Proceso para facturar totus')

INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('CUENTABANCO','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('CAMBFACT','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('CLASEPRECIO','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('RESUMENTOTTUS','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('CONDPAGO','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('LIBERACION','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('SUBCUENTABANCOD','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('CUENTABANCO0','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('SUBCUENTABANCO','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('AREPT','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('SUBCUENTABANCOO','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('CAFETERIA','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('ALMACEN','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('ORDEN','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('MPRECIO','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('CUENTABANCOD','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('CAFETERIAS','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('VOUCHER','Nueva Descripcion')
INSERT INTO TB_RESTRICCIONTIPO (TIPO,DESCRIPCION_TIPO) VALUES ('CONDICIONEMB','Nueva Descripcion')


INSERT INTO TB_RESTRICCIONTIPO (tipo,descripcion_tipo) VALUES ('MOVECUOTA','MoverCuota')



SELECT * FROM TB_RESTRICCIONTIPO


USE [CA2015APP]
GO


alter PROC PV_LISTAR_RESTTIPO
-- FUNCION	: LISTAR  LA TABLA TB_RESTRICCIONTIPO PARA USO PV [AM2014app]
-- AUTOR	: Gasla Baudat Laisson 
-- Ultima Fecha Modificacion : 03/02/2015
-- Sistema  : Solomon v4
@parm1 varchar(15) 
as 
begin
select * from tb_restricciontipoX where tipo like @parm1 ORDER BY TIPO
end


ALTER VIEW TB_RESTRICCIONTIPOX
-- FUNCION	: VISTA DE LA TABLA TB_RESTRICCIONTIPO
-- AUTOR	: Gasla Baudat Laisson 
-- Ultima Fecha Modificacion : 23/05/2015
-- Sistema  : Solomon v4
AS
SELECT * FROM TB_RESTRICCIONTIPO



ALTER proc TSP_LISTAR_XAMREST
-- FUNCION	: LISTAR Tabla XAMRESTRICCION PARA SPREAD1 [AM2015APP]
-- AUTOR	: Gasla Baudat Laisson 
-- Ultima Fecha Modificacion : 23/05/2015
-- Sistema  : Solomon v4
@parm1 varchar(47),--USER ID
@parm2 varchar(15),--TIPO
@parm3 varchar(30)--DATO
AS
BEGIN 
SELECT * FROM XAMRESTRICCIONX WHERE USERID=@parm1 AND TIPO LIKE @parm2 and DATO LIKE @PARM3
order by TIPO,DATO
END



ALTER VIEW XAMRESTRICCIONX
-- FUNCION	:VISTA DE LA TABLA XAMRESTRICCION
-- AUTOR	: Gasla Baudat Laisson 
-- Ultima Fecha Modificacion : 23/05/2015
-- Sistema  : Solomon v4
AS
SELECT * FROM XAMRESTRICCION



 

